{
 "title": "Home",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Snowflake",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "dataset": "snowflake",
     "rawSql": "SELECT date_time, connections, download, upload FROM snowflake.snowflake"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum_upload FROM snowflake.snowflake;"
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum_download FROM snowflake.snowflake;"
    }
   ]
  },
  {
   "title": "Verbindungen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum_connections FROM snowflake.snowflake;"
    }
   ]
  }
 ]
}