version: "3.7"
services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: mariadb
    hostname: mariadb
    restart: always

    volumes:
      - mariadb:/var/lib/mysql
      - mariadb_config:/config

    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: "erik"
      MYSQL_PASSWORD: $MYSQL_PASSWORD

    ports:
      - 3306:3306

    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1
      interval: 60s
      timeout: 5s
      retries: 5

    labels:
      # Watchtower - Container automatisch aktualisieren
      - "com.centurylinklabs.watchtower.enable=true"

    networks:
      - intern  # Dieser Dienst tritt dem Netzwerk "intern" bei

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    container_name: phpmyadmin
    hostname: phpmyadmin

    ports:
      - 9010:80

    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb                     # Datenbank IP-Adresse
      PMA_PORT: 3306                      # Datenbank Port (3306 - MariaDB)
      PMA_PASSWORD: $MYSQL_ROOT_PASSWORD  # Datenbank Passwort
      PMA_USER: root                      # Datenbank User

    depends_on:
      - mariadb

    labels:
      # Watchtower - Container automatisch aktualisieren
      - "com.centurylinklabs.watchtower.enable=true"

    networks:
      - intern  # Dieser Dienst tritt dem Netzwerk "intern" bei

volumes:
  mariadb:
    name: mariadb
  mariadb_config:
    name: mariadb_config
   
networks:
  intern:
    external: true
