version: '3'
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik
    restart: always

    security_opt:
      - no-new-privileges:true

    networks:
      - extern

    ports:
      - 80:80
      - 443:443
      - 9030:8080  # Dashboard

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/erik/docker/config_files/traefik/traefik.yml:/traefik.yml:ro
      - /home/erik/docker/config_files/traefik/acme.json:/acme.json
      - /home/erik/docker/config_files/traefik/dynamic_conf.yml:/dynamic_conf.yml

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`$TLD`)"                              # Ändern !
      - "traefik.http.middlewares.traefik-auth.basicauth.users=$TRAEFIKUSER"          # Ändern !
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`$TLD`)"    
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "providers.file.filename=/dynamic_conf.yml"
      - "traefik.http.routers.traefik-secure.middlewares=secHeaders@file,traefik-auth"

      # Watchtower - Container automatisch aktualisieren
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  extern:
    external: true
