api:
  dashboard: true

log:
  level: INFO

accessLog: {}

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "./dynamic_conf.yml"

certificatesResolvers:
  http:
    acme:
      email: erik@xxxxxx.com
      storage: acme.json
      httpChallenge:
        entryPoint: http

serversTransport:
  insecureSkipVerify: true
