version: "3.9"

services:
  tasmo-admin:
    image: ghcr.io/tasmoadmin/tasmoadmin:latest
    
    container_name: tasmo-admin
    hostname: tasmo-admin

    volumes:
      - tasmo-admin:/home/pi/Docker/TasmoAdmin/data:/data

    restart: always

    ports:
      - 9020:80
      
    labels:
      # Watchtower - Container automatisch aktualisieren
      - "com.centurylinklabs.watchtower.enable=true"

    networks:
      - intern

volumes:
  tasmo-admin:
    name: tasmo-admin

networks:
  intern:
    external: true
