version: "3.7"
services:
  mariadb:
    image: linuxserver/mariadb:latest

    container_name: mariadb
    hostname: mariadb

    restart: always

    volumes:
      - mariadb:/var/lib/mysql

    environment:
      TZ: $TIMEZONE                               # Zeitzone
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD   # Root Passwort
      MYSQL_DATABASE: $USER                       # Datenbank
      MYSQL_USER: $USER                           # Benutzername
      MYSQL_PASSWORD: $MYSQL_PASSWORD             # Passwort

    ports:
      - 3306:3306

    healthcheck:
      test:  mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1
      interval: 60s
      timeout: 5s
      retries: 5

    labels:
      # Watchtower - Container automatisch überwachen, melden wenn neue Version verfügbar ist
      - "com.centurylinklabs.watchtower.monitor-only=true"

volumes:
  mariadb:
    name: mariadb