version: "3"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    hostname: uptime-kuma
    
    ports:
      - 9070:3001

    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock       # Für das Monitoren von Docker-Container auf dem Host

    labels:
      # Watchtower - Container automatisch aktualisieren
      - "com.centurylinklabs.watchtower.enable=true"

    restart: always

volumes:
  uptime-kuma:
    name: uptime-kuma