version: "3.7"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    hostname: influxdb

    ports:
      - '9030:8086'
    
    networks:
      - intern

    volumes:
      - influxdb-storage:/var/lib/influxdb


    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: $DGUSER
      DOCKER_INFLUXDB_INIT_PASSWORD: $DBPASS
      DOCKER_INFLUXDB_INIT_ORG: $DBORG
      DOCKER_INFLUXDB_INIT_BUCKET: $DBBUCKET

    labels:
      # Watchtower - Container automatisch aktualisieren
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
    influxdb-storage:

networks:
  intern:
    external: true